---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thiago-blog
  namespace: landim
  labels:
    app: goapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: goapi
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: thiago-blog
  namespace: landim
spec:
  selector:
    app: goapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: landim
  name: thiago-blog-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
  - host: nosi.cv/
    http:
      paths:
        - path: /
          backend:
            serviceName: thiago-blog-service
            servicePort: 80
